// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyuqpnvrgvtxuwgbzdai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5dXFwbnZyZ3Z0eHV3Z2J6ZGFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NjU3MjcsImV4cCI6MjA2ODU0MTcyN30.3CmPwoSkRw83YPi7QOOXluC5HSh4RwwpPl16wm8GeY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});